In [2]:
import numpy as np #넘파이를 설치 했고 넘파이를 np라고 부를거임

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [4]:
%timeit my_list2 = [i *2 for i in my_list] #%timeit : 속도측정
%timeit my_arry2 = my_array * 2 

49.7 ms ± 1.27 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.02 ms ± 77.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
] #2차원 함수에 소수 넣어서 모든 형태를 소수로 바꾸줌
data = np.array(a) #np에 array함수 실행
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [8]:
#0차원 : 스칼라(scala), 1차원 : 벡터(vector), 
#2차원 : 행렬(matrix), 3차원 : 텐서(tenser)
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [9]:
print(data.shape) #데이터의 모양을 찍어줘//덩어리 2개 안에 데이터 3개
print(data.dtype) #안에 있는 데이터의 세부정보, float=소수, 64=64비트 사용

(2, 3)
float64


## ndarray 생성하기
- n차원의 배열 혹은 행렬

In [11]:
data1= [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [18]:
arr2 = np.array([[1.1, 2.2], [3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [19]:
print(arr1.ndim) #ndim = 몇 차원인가요?
print(arr2.ndim)

1
2


In [21]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [26]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5, 5)))  #(5,5)형태의 0으로 가득찬 
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[4.67296746e-307 1.69121096e-306]
  [8.90067740e-308 1.42413555e-306]]

 [[1.78019082e-306 1.37959740e-306]
  [6.23057349e-307 1.42419530e-306]]]


In [27]:
print(np.arange(10)) #0-9까지 형태가 있는 어랜지

[0 1 2 3 4 5 6 7 8 9]


## ndarray 자료형

In [30]:
arr1 = np.array([1, 2, 3], dtype=np.float64) #dtype는 데이터 타입 설정
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [33]:
 #생성 완료 후 형변환
#int -> flo
arr1 = np.array([1, 2, 3]) 
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [36]:
#flo -> int
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 산술 연산

In [43]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr) #같은 위치에 있는 숫자끼리 곱함
print(arr + arr)
print(1 / arr)
print(arr ** 3) #모든 숫자 세제곱

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [47]:
#비교
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2) #같은 위치에 있는 값끼리 비교함
print(arr == 3) #3이 있는 위치만 골라주셈

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인과 슬라이싱

In [49]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
print(arr[7]) #[n]번째 인덱스 뽑아주삼
print(arr[2:5]) # 2-5까지 데이터 뽑아주삼

7
[10 10 10]


In [55]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [56]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [60]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [63]:
print(arr[1][1]) #2차원 데이터에 접근, 5에 접근
print(arr[1, 1]) #위에꺼 이렇게 써도 됨

5
5


In [108]:
arr3d = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[11, 12, 13], [14, 15, 16], [17, 18, 19]],
    [[21, 22, 23], [24, 25, 26], [27, 28, 29]]
])

In [113]:
print(arr3d[2][0][1]) #3차원 데이터에 접근
print(arr3d[2, 0, 1])

22
22


In [114]:
arr3d[:1] #0번째 데이터 부터 1번째 데이터 까지 슬라이싱

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [115]:
arr3d[:1, 1:, 2:] #1이상 2미만, [0:1, 1:, 2:] 하면 차원 줄어듬

array([[[6],
        [9]]])

In [116]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  21   22   23]
  [  24   25   26]
  [  27   28   29]]]


## 불리언 값으로 선택

In [70]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [71]:
#hong의 데이터만 고르고 싶음
names == 'hong'

array([ True, False,  True, False])

In [72]:
#데이터를 인덱스 접근 할 때  결과가 hong이냐
#data[[True, False, True, False]] 
data[names == 'hong'] #특정 조건에 맞는 데이터를 고를 때

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [74]:
#특정 과목, 점수만 따로 보고 싶다
print(data[names == 'hong', 1]) #데이터 접근
print(data[names == 'hong', :1]) #슬라이싱 접근

['60' '70']
[['math']
 ['eng']]


In [79]:
print(names != 'hong') #지금있는 데이터가 hong이 아닌가요?
print(~(names == 'hong')) #계산결과를 먼저 만들고 역을 취해줌 = hong이 아닌 사람 골라주셈

[False  True False  True]
[False  True False  True]


In [81]:
#결과를 comd에 저장
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)
- 특정행을 갖고올때

In [86]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i #i번째를 i로 바꿈
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [90]:
arr[[4, 3, 0, 5]] #특정한 요소에 있는 데이터를 골라낼때

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [89]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [95]:
arr = np.arange(32).reshape(8, 4) #0부터 32까지 배열을 (8,4) 규격으로 만듬
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [97]:
arr[[1, 5], [2, 3]]

array([ 6, 23])

In [100]:
arr[[1, 5]][:, [2, 3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치
- 배열 축을 바꾸는거

In [102]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [104]:
print(arr.T) #\(0-14)을 축으로 숫자 배열 바꿈

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [107]:
#행열의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [121]:
samples = np.random.standard_normal(size=(3, 3))
print(samples)

[[ 1.04417048  1.40564725  0.26188326]
 [ 0.40509125 -0.82387776 -0.9946003 ]
 [-2.36748517  1.20152376 -1.7519081 ]]


In [125]:
arr1 = np.sqrt(samples) #arr1에 저장한 상태 //nan = 숫자가 아닙니다 = 결측치  
print(arr1)

[[1.0218466  1.18559995 0.51174531]
 [0.63646779        nan        nan]
 [       nan 1.09614039        nan]]


C:\Users\1-02\AppData\Local\Temp\ipykernel_7284\1188358759.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples) #arr1에 저장한 상태 //nan = 숫자가 아닙니다 = 결측치


In [126]:
arr2 = np.abs(samples) #abs = 절대값으로 바꿔줌
print(arr2)

[[1.04417048 1.40564725 0.26188326]
 [0.40509125 0.82387776 0.9946003 ]
 [2.36748517 1.20152376 1.7519081 ]]


In [127]:
np.isnan(arr1)

array([[False, False, False],
       [False,  True,  True],
       [ True, False,  True]])