In [2]:
import numpy as np

my_list = list(range(10000))
my_array = np.arange(10000)

In [3]:
%timeit my_list2 = [i *2 for i in my_list]
%timeit my_arry2 = my_array * 2

326 μs ± 31.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.62 μs ± 217 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [6]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [7]:
data1= [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [9]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [11]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5, 5)))
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [13]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [15]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [16]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [22]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[ True False False]
 [False False  True]]


In [25]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(arr[7])
print(arr[2:5])

7
[2 3 4]


In [27]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr[1][2])
print(arr[1, 1])

6
5


In [41]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [42]:
names == 'hong'

array([ True, False,  True, False])

In [43]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [45]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [46]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [49]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [50]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [54]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [55]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [58]:
arr[[1, 3], [2, 3]]

array([ 6, 15])

In [59]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
