In [2]:
import numpy as np

my_list = list(range(10000))
my_array = np.arange(10000)

In [3]:
%timeit my_list2 = [i *2 for i in my_list]
%timeit my_arry2 = my_array * 2

326 μs ± 31.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
6.62 μs ± 217 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
a = [
    [1, 1.2, 3],
    [-123, 123, 0]
]
data = np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [5]:
print(data * 10)
print(data + data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [6]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


In [7]:
data1= [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [9]:
print(arr1.ndim)
print(arr2.ndim)

1
2


In [11]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5, 5)))
print(np.empty((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [13]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [15]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64)
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [16]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 = arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print(arr ** 3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[  1   8  27]
 [ 64 125 216]]


In [22]:
arr2 = np.array([[3, 2, 1], [1, 2, 3]])
print(arr)
print(arr2)
print(arr > arr2)
print(arr2 == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[ True False False]
 [False False  True]]


In [25]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(arr[7])
print(arr[2:5])

7
[2 3 4]


In [27]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [35]:
print(arr[1][2])
print(arr[1, 1])

6
5


In [41]:
names = np.array(['hong', 'kim', 'hong', 'kim'])
data = np.array([['math', 60], ['math', 90], ['eng', 70], ['eng', 50]])

In [42]:
names == 'hong'

array([ True, False,  True, False])

In [43]:
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [45]:
print(data[names == 'hong', 1])
print(data[names == 'hong', :1])

['60' '70']
[['math']
 ['eng']]


In [46]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [49]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [50]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [54]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [55]:
arr = np.arange(32).reshape(8, 4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [58]:
arr[[1, 3], [2, 3]]

array([ 6, 15])

In [59]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/titanic.csv')

In [3]:
import seaborn as sns

In [4]:
df = sns.load_dataset('titanic')

In [5]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [6]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [7]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [8]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [11]:
print(type(df['who']))

<class 'pandas.core.series.Series'>


In [12]:
df['who'].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [13]:
df['pclass'].value_counts()

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [14]:
df['pclass'].astype('int32')

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: pclass, Length: 891, dtype: int32

In [15]:
df['pclass'].astype('category').head()

0    3
1    1
2    3
3    1
4    3
Name: pclass, dtype: category
Categories (3, int64): [1, 2, 3]

In [16]:
df.sort_index(ascending=False).head()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
890         0       3    male  32.0      0      0   7.75        Q   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
887         1       1  female  19.0      0      0  30.00        S   First   
886         0       2    male  27.0      0      0  13.00        S  Second   

       who  adult_male deck  embark_town alive  alone  
890    man        True  NaN   Queenstown    no   True  
889    man        True    C    Cherbourg   yes   True  
888  woman       False  NaN  Southampton    no  False  
887  woman       False    B  Southampton   yes   True  
886    man        True  NaN  Southampton    no   True

In [18]:
df.sort_index(ascending=False).head()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
890         0       3    male  32.0      0      0   7.75        Q   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
887         1       1  female  19.0      0      0  30.00        S   First   
886         0       2    male  27.0      0      0  13.00        S  Second   

       who  adult_male deck  embark_town alive  alone  
890    man        True  NaN   Queenstown    no   True  
889    man        True    C    Cherbourg   yes   True  
888  woman       False  NaN  Southampton    no  False  
887  woman       False    B  Southampton   yes   True  
886    man        True  NaN  Southampton    no   True

In [21]:
df.sort_values('age', ascending=False).head(5)

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
630         1       1  male  80.0      0      0  30.0000        S  First  man   
851         0       3  male  74.0      0      0   7.7750        S  Third  man   
493         0       1  male  71.0      0      0  49.5042        C  First  man   
96          0       1  male  71.0      0      0  34.6542        C  First  man   
116         0       3  male  70.5      0      0   7.7500        Q  Third  man   

     adult_male deck  embark_town alive  alone  
630        True    A  Southampton   yes   True  
851        True  NaN  Southampton    no   True  
493        True  NaN    Cherbourg    no   True  
96         True    A    Cherbourg    no   True  
116        True  NaN   Queenstown    no   True

In [23]:
df.sort_values('class').head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
445         1       1    male   4.0      0      2  81.8583        S  First   
310         1       1  female  24.0      0      0  83.1583        C  First   
309         1       1  female  30.0      0      0  56.9292        C  First   

       who  adult_male deck  embark_town alive  alone  
445  child       False    A  Southampton   yes  False  
310  woman       False    C    Cherbourg   yes   True  
309  woman       False    E    Cherbourg   yes   True

In [25]:
df.sort_values(['fare', 'age'], ascending=[False, True]).head(50)

survived  pclass     sex    age  sibsp  parch      fare embarked  class  \
258         1       1  female  35.00      0      0  512.3292        C  First   
737         1       1    male  35.00      0      0  512.3292        C  First   
679         1       1    male  36.00      0      1  512.3292        C  First   
27          0       1    male  19.00      3      2  263.0000        S  First   
88          1       1  female  23.00      3      2  263.0000        S  First   
341         1       1  female  24.00      3      2  263.0000        S  First   
438         0       1    male  64.00      1      4  263.0000        S  First   
311         1       1  female  18.00      2      2  262.3750        C  First   
742         1       1  female  21.00      2      2  262.3750        C  First   
118         0       1    male  24.00      0      1  247.5208        C  First   
299         1       1  female  50.00      0      1  247.5208        C  First   
700         1       1  female  18.00      1      0  227.5250        C  First   
716         1       1  female  38.00      0      0  227.5250        C  First   
380         1       1  female  42.00      0      0  227.5250        C  First   
557         0       1    male    NaN      0      0  227.5250        C  First   
527         0       1    male    NaN      0      0  221.7792        S  First   
377         0       1    male  27.00      0      2  211.5000        C  First   
689         1       1  female  15.00      0      1  211.3375        S  First   
730         1       1  female  29.00      0      0  211.3375        S  First   
779         1       1  female  43.00      0      1  211.3375        S  First   
318         1       1  female  31.00      0      2  164.8667        S  First   
856         1       1  female  45.00      1      1  164.8667        S  First   
332         0       1    male  38.00      0      1  153.4625        S  First   
609         1       1  female  40.00      0      0  153.4625        S  First   
268         1       1  female  58.00      0      1  153.4625        S  First   
305         1       1    male   0.92      1      2  151.5500        S  First   
297         0       1  female   2.00      1      2  151.5500        S  First   
708         1       1  female  22.00      0      0  151.5500        S  First   
498         0       1  female  25.00      1      2  151.5500        S  First   
195         1       1  female  58.00      0      0  146.5208        C  First   
31          1       1  female    NaN      1      0  146.5208        C  First   
373         0       1    male  22.00      0      0  135.6333        C  First   
269         1       1  female  35.00      0      0  135.6333        S  First   
325         1       1  female  36.00      0      0  135.6333        C  First   
319         1       1  female  40.00      1      1  134.5000        C  First   
337         1       1  female  41.00      0      0  134.5000        C  First   
660         1       1    male  50.00      2      0  133.6500        S  First   
334         1       1  female    NaN      1      0  133.6500        S  First   
802         1       1    male  11.00      1      2  120.0000        S  First   
435         1       1  female  14.00      1      2  120.0000        S  First   
390         1       1    male  36.00      1      2  120.0000        S  First   
763         1       1  female  36.00      1      2  120.0000        S  First   
393         1       1  female  23.00      1      0  113.2750        C  First   
215         1       1  female  31.00      1      0  113.2750        C  First   
659         0       1    male  58.00      0      2  113.2750        C  First   
550         1       1    male  17.00      0      2  110.8833        C  First   
581         1       1  female  39.00      1      1  110.8833        C  First   
698         0       1    male  49.00      1      1  110.8833        C  First   
306         1       1  female    NaN      0      0  110.8833        C  First   
307  

In [26]:
df.loc[3]

survived                 1
pclass                   1
sex                 female
age                   35.0
sibsp                    1
parch                    0
fare                  53.1
embarked                 S
class                First
who                  woman
adult_male           False
deck                     C
embark_town    Southampton
alive                  yes
alone                False
Name: 3, dtype: object

In [27]:
df.loc[3, 'class']

'First'

In [28]:
df.loc[3, ['class', 'age'] ]

class    First
age       35.0
Name: 3, dtype: object

In [29]:
df.loc[2:5]

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   
5         0       3    male   NaN      0      0   8.4583        Q  Third   

     who  adult_male deck  embark_town alive  alone  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True

In [30]:
df.loc[2:5, ['pclass', 'who']]

pclass    who
2       3  woman
3       1  woman
4       3    man
5       3    man

In [31]:
df[['class', 'age']].head

<bound method NDFrame.head of       class   age
0     Third  22.0
1     First  38.0
2     Third  26.0
3     First  35.0
4     Third  35.0
..      ...   ...
886  Second  27.0
887   First  19.0
888   Third   NaN
889   First  26.0
890   Third  32.0

[891 rows x 2 columns]>

In [32]:
df.loc[:3, 'class':'deck']

class    who  adult_male deck
0  Third    man        True  NaN
1  First  woman       False    C
2  Third  woman       False  NaN
3  First  woman       False    C

In [33]:
condition = df['who'] == 'man'

In [34]:
df[condition].head()

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
0          0       3  male  22.0      1      0   7.2500        S  Third  man   
4          0       3  male  35.0      0      0   8.0500        S  Third  man   
5          0       3  male   NaN      0      0   8.4583        Q  Third  man   
6          0       1  male  54.0      0      0  51.8625        S  First  man   
12         0       3  male  20.0      0      0   8.0500        S  Third  man   

    adult_male deck  embark_town alive  alone  
0         True  NaN  Southampton    no  False  
4         True  NaN  Southampton    no   True  
5         True  NaN   Queenstown    no   True  
6         True    E  Southampton    no   True  
12        True  NaN  Southampton    no   True

In [35]:
df.loc[condition].head()

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  \
0          0       3  male  22.0      1      0   7.2500        S  Third  man   
4          0       3  male  35.0      0      0   8.0500        S  Third  man   
5          0       3  male   NaN      0      0   8.4583        Q  Third  man   
6          0       1  male  54.0      0      0  51.8625        S  First  man   
12         0       3  male  20.0      0      0   8.0500        S  Third  man   

    adult_male deck  embark_town alive  alone  
0         True  NaN  Southampton    no  False  
4         True  NaN  Southampton    no   True  
5         True  NaN   Queenstown    no   True  
6         True    E  Southampton    no   True  
12        True  NaN  Southampton    no   True

In [36]:
df.loc[condition, 'age'] = 100

In [37]:
df.head()

survived  pclass     sex    age  sibsp  parch     fare embarked  class  \
0         0       3    male  100.0      1      0   7.2500        S  Third   
1         1       1  female   38.0      1      0  71.2833        C  First   
2         1       3  female   26.0      0      0   7.9250        S  Third   
3         1       1  female   35.0      1      0  53.1000        S  First   
4         0       3    male  100.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [39]:
cond1 = df['fare'] > 30
cond2 = df['who'] == 'woman'

In [40]:
cond2.head()

0    False
1     True
2     True
3     True
4    False
Name: who, dtype: bool

In [41]:
df.loc[cond1 & cond2].head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1          1       1  female  38.0      1      0  71.2833        C  First   
3          1       1  female  35.0      1      0  53.1000        S  First   
25         1       3  female  38.0      1      5  31.3875        S  Third   

      who  adult_male deck  embark_town alive  alone  
1   woman       False    C    Cherbourg   yes  False  
3   woman       False    C  Southampton   yes  False  
25  woman       False  NaN  Southampton   yes  False

In [42]:
df.iloc[1, 3]

np.float64(38.0)

In [43]:
cond = df['fare'] < 30
df['fare'].where(cond, 1).tail

<bound method NDFrame.tail of 0       7.250
1       1.000
2       7.925
3       1.000
4       8.050
        ...  
886    13.000
887     1.000
888    23.450
889     1.000
890     7.750
Name: fare, Length: 891, dtype: float64>

In [44]:
cond = df['embarked'].isin(['Q', 'S'])
df.loc[cond]

survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
0           0       3    male  100.0      1      0   7.2500        S   Third   
2           1       3  female   26.0      0      0   7.9250        S   Third   
3           1       1  female   35.0      1      0  53.1000        S   First   
4           0       3    male  100.0      0      0   8.0500        S   Third   
5           0       3    male  100.0      0      0   8.4583        Q   Third   
..        ...     ...     ...    ...    ...    ...      ...      ...     ...   
885         0       3  female   39.0      0      5  29.1250        Q   Third   
886         0       2    male  100.0      0      0  13.0000        S  Second   
887         1       1  female   19.0      0      0  30.0000        S   First   
888         0       3  female    NaN      1      2  23.4500        S   Third   
890         0       3    male  100.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
5      man        True  NaN   Queenstown    no   True  
..     ...         ...  ...          ...   ...    ...  
885  woman       False  NaN   Queenstown    no  False  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
890    man        True  NaN   Queenstown    no   True  

[721 rows x 15 columns]

In [45]:
tips = sns.load_dataset('tips')

In [46]:
cond1 = tips['sex'] == 'Male'
cond2 = tips['smoker'] == 'Yes'
tips.loc[cond1 & cond2].sort_values('tip', ascending=False).head(10)

total_bill    tip   sex smoker   day    time  size
170       50.81  10.00  Male    Yes   Sat  Dinner     3
183       23.17   6.50  Male    Yes   Sun  Dinner     4
181       23.33   5.65  Male    Yes   Sun  Dinner     2
211       25.89   5.16  Male    Yes   Sat  Dinner     4
172        7.25   5.15  Male    Yes   Sun  Dinner     2
83        32.68   5.00  Male    Yes  Thur   Lunch     2
95        40.17   4.73  Male    Yes   Fri  Dinner     4
107       25.21   4.29  Male    Yes   Sat  Dinner     2
106       20.49   4.06  Male    Yes   Sat  Dinner     2
189       23.10   4.00  Male    Yes   Sun  Dinner     3

In [49]:
cond1 = tips['size'] >= 5
cond2 = tips['time'] == 'Dinner'

cond3 = tips['smoker'] == 'No'
cond4 = tips['day'].isin(['Sat', 'Sun'])

tips.loc[(cond1 & cond2) & (cond3 & cond4)][['total_bill', 'tip']]
#tips.loc[(cond1 & cond2) & (cond3 & cond4), ['total_bill', 'tip']]

total_bill   tip
155       29.85  5.14
156       48.17  5.00
185       20.69  5.00
187       30.46  2.00
216       28.15  3.00

In [50]:
df = sns.load_dataset('titanic')
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [51]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [53]:
df.describe(include='object')

sex embarked  who  embark_town alive
count    891      889  891          889   891
unique     2        3    3            3     2
top     male        S  man  Southampton    no
freq     577      644  537          644   549

In [54]:
df.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [55]:
df['age'].count()

np.int64(714)

In [56]:
df['age'].mean()

np.float64(29.69911764705882)

In [57]:
df.mean(numeric_only=True)

survived       0.383838
pclass         2.308642
age           29.699118
sibsp          0.523008
parch          0.381594
fare          32.204208
adult_male     0.602694
alone          0.602694
dtype: float64

In [59]:
cond = df['adult_male'] == True
df.loc[cond, 'fare'].mean()

np.float64(24.864181750465548)

In [60]:
cond1 = df['fare'] >= 30
cond2 = df['fare'] <= 40

cond3 = df['pclass'] == 1

df.loc[cond1 & cond2 & cond3, 'age'].mean()

np.float64(44.095238095238095)

In [61]:
numbers = [1, 2, 10, 11, 100, 1000]
pd.Series(numbers).mean()

np.float64(187.33333333333334)

In [62]:
pd.Series(numbers).median()

np.float64(10.5)

In [63]:
mean_value = df['age'].mean()
median_value = df['age'].median()
print(mean_value, median_value)

29.69911764705882 28.0


In [64]:
df.sum(numeric_only=True)

survived        342.0000
pclass         2057.0000
age           21205.1700
sibsp           466.0000
parch           340.0000
fare          28693.9493
adult_male      537.0000
alone           537.0000
dtype: float64

In [65]:
df['fare'].sum()

np.float64(28693.9493)

In [67]:
df['fare'].cumsum()

0          7.2500
1         78.5333
2         86.4583
3        139.5583
4        147.6083
          ...    
886    28602.7493
887    28632.7493
888    28656.1993
889    28686.1993
890    28693.9493
Name: fare, Length: 891, dtype: float64

In [68]:
df['age'].cumprod()

C:\Users\1-02\Desktop\DAMF2\pandas\venv\Lib\site-packages\numpy\_core\fromnumeric.py:57: RuntimeWarning: overflow encountered in accumulate
  return bound(*args, **kwds)


0            22.0
1           836.0
2         21736.0
3        760760.0
4      26626600.0
          ...    
886           inf
887           inf
888           NaN
889           inf
890           inf
Name: age, Length: 891, dtype: float64

In [70]:
fare_mean = df['fare'].mean()

total = ((df['fare'] - fare_mean) ** 2).sum()
total_count = df['fare'].count() - 1

my_var = total / total_count
print(my_var)

2469.436845743116


In [71]:
df['fare'].var(ddof=0)

np.float64(2466.665311685043)

In [73]:
import numpy as np
np.sqrt(df['fare'].var())

np.float64(49.6934285971809)

In [74]:
df['fare'].std()

np.float64(49.6934285971809)

In [88]:
import numpy as np
np.sqrt(df['fare'].var())

np.float64(49.6934285971809)

In [101]:
df[['age', 'fare']].agg(['max', 'min']) 

age      fare
max  80.00  512.3292
min   0.42    0.0000

In [102]:
df['age'].median()

np.float64(28.0)

In [103]:
df['age'].quantile(0.5)

np.float64(28.0)

In [104]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [105]:
df['who'].nunique()

3

In [109]:
df.corr(numeric_only=True)

survived    pclass       age     sibsp     parch      fare  \
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500   
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067   
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024   
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832   

            adult_male     alone  
survived     -0.557080 -0.203367  
pclass        0.094035  0.135207  
age           0.280328  0.198270  
sibsp        -0.253586 -0.584471  
parch        -0.349943 -0.583398  
fare         -0.182024 -0.271832  
adult_male    1.000000  0.404744  
alone         0.404744  1.000000

In [110]:
df.corr(numeric_only=True)['survived']

survived      1.000000
pclass       -0.338481
age          -0.077221
sibsp        -0.035322
parch         0.081629
fare          0.257307
adult_male   -0.557080
alone        -0.203367
Name: survived, dtype: float64

In [111]:
df_copy = df.copy()

In [112]:
id(df_copy), id(df)

(2063713904000, 2063686183952)

In [113]:
df_copy.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [115]:
df_copy.loc[0, 'age'] = 99999

In [117]:
df_copy.head(1)

survived  pclass   sex      age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  99999.0      1      0  7.25        S  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False

In [120]:
df.head(1)

survived  pclass   sex   age  sibsp  parch  fare embarked  class  who  \
0         0       3  male  22.0      1      0  7.25        S  Third  man   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False

In [121]:
df_copy = df.copy()

In [122]:
df_copy.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [127]:
df_copy.isna().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [128]:
df_copy.notnull().sum()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [134]:
cond = df_copy['age'].isnull()
df_copy.loc[cond, 'age'] = 30

In [132]:
df_copy

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  30.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  30.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  30.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  30.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female  30.0      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  30.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [137]:
df_copy = df.copy()

In [140]:
df_copy.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [143]:
df_copy['age'] = df_copy['age'].fillna(100)

In [144]:
df_copy

survived  pclass     sex    age  sibsp  parch     fare embarked   class  \
0           0       3    male   22.0      1      0   7.2500        S   Third   
1           1       1  female   38.0      1      0  71.2833        C   First   
2           1       3  female   26.0      0      0   7.9250        S   Third   
3           1       1  female   35.0      1      0  53.1000        S   First   
4           0       3    male   35.0      0      0   8.0500        S   Third   
..        ...     ...     ...    ...    ...    ...      ...      ...     ...   
886         0       2    male   27.0      0      0  13.0000        S  Second   
887         1       1  female   19.0      0      0  30.0000        S   First   
888         0       3  female  100.0      1      2  23.4500        S   Third   
889         1       1    male   26.0      0      0  30.0000        C   First   
890         0       3    male   32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [145]:
df_copy['deck'].value_counts()

deck
C    59
B    47
D    33
E    32
A    15
F    13
G     4
Name: count, dtype: int64

In [146]:
df_copy['deck'].fillna('C')

0      C
1      C
2      C
3      C
4      C
      ..
886    C
887    B
888    C
889    C
890    C
Name: deck, Length: 891, dtype: category
Categories (7, object): ['A', 'B', 'C', 'D', 'E', 'F', 'G']

In [147]:
age_mean = df_copy['age'].mean()

In [149]:
df_copy['age'] = df_copy['age'].fillna(age_mean)

In [150]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          891 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
